app/controllers/UserController.php
<?php

class UserController extends AdminController
{
	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex($export=false){
		$model = new User();
		$model->unsetAttributes();

		if(isset($_GET['User']))
		{
			$model->attributes = $_GET['User'];
		}

		if($export)
		{
			Yii::import('application.components.exportXls.ExportXLSHelper');
			$helper = new ExportXLSHelper();
			$helper->model = $model;
			$helper->filename = 'usuarios-';
			$helper->header = 'Usuarios al ';
			$dp = $model->search();
			$dp->pagination = false;
			$helper->data = $dp->getData();
			$helper->attributes = $model->getXlsAttributes();
			$helper->generateSheet();
			app()->end();
		}

		$this->render('index', array(
			'model' => $model,
		));
	}

	public function actionChangeAttributeUser()
	{
		Yii::import('bootstrap.widgets.TbEditableSaver');
		$es = new TbEditableSaver('User');
	    $es->update();
	}

	public function actionDelete($id, $key) {
		$model = User::model()->findByPk(CPropertyValue::ensureInteger($id));

		if (Yii::app()->getRequest()->getIsPostRequest() && $model instanceof User &&
			strcmp($key, uKey("deleteUser".$model->primaryKey))==0) 
		{			
			try {
				$model->delete();
			} catch (Exception $e) {
				throw new CHttpException(500, Yii::t('app', 'The User is being used and cannot be deleted'));
			}
			if (!Yii::app()->getRequest()->getIsAjaxRequest())
			{
				$this->redirect(array('index'));
			}
		} else{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}

	/**
	 * updates a new user
	 */ 
	public function actionUpdate($id, $key)
	{
		$model = User::model()->findByPk(CPropertyValue::ensureInteger($id));
		
		if($model instanceof User && strcmp(uKey("updateUser".$model->primaryKey), $key)==0)
		{
			if(isset($_POST['User']))
	       	{
		        $model->attributes=$_POST['User'];
		        if($model->save())
		        {
		            $this->redirect(array('index'));
		        }
	        }


			$this->render('form', array('model'=>$model, 'update'=>true));
			return;
		}

		throw new CHttpException(404, Yii::t('app', 'Invalid user'));
	}	

	/**
	 * Creates a new User
	 */ 
	public function actionCreate()
	{
		$model = new User('create');
		
		if(isset($_POST['User']))
       	{
	        $model->attributes=$_POST['User'];
	        $model->_signature=CUploadedFile::getInstance($model,'_signature');
	        
	        if($model->save())
	        {
	            $this->redirect(array('index'));
	        }
        }
		$this->render('form', array('model'=>$model));
	}

	public function actions()
	{
		return array(
			'toggle' => array(
				'class'=>'bootstrap.actions.TbToggleAction',
				'modelName' => 'User',
			),
		);
	}

	/**
	 * Displays details of users and permissions
	 * @param  int $idUser
	 */
	public function actionUserRolesPermissions($idUser, $key)
	{
		$user = User::model()->findByPk($idUser);
		if ($user instanceof User && strcmp($key, uKey("perms".$user->primaryKey))==0)
		{	
			$roles = Roles::model()->findAll('visible = 1');

			$this->renderPartial('userRoles', array(
				'user'=>$user,
				'roles'=>$roles,
			), false, true);
			return;
		}

		throw new CHttpException(404, "Invalid user");
	}

	/**
	 * Check whether a user identified with pk $user has role identified with pk $role
	 * @param int $idUser
	 * @param int $idRole
	 * @return string Json encoded array used to display if user has a role or not via ajax
	 */ 
	public function actionToggleRolesForUser($idUser, $idRole)
	{
		$text = Yii::t('app', 'No');
		$idUser = CPropertyValue::ensureInteger($idUser);
		$idRole = CPropertyValue::ensureInteger($idRole);
		
		$uhr = UserHasRoles::model()->findByPk(array('idUser'=>$idUser, 'rolesId'=>$idRole));
		
		if ($uhr instanceof UserHasRoles)
		{
			//Role already exists. Delete it.
			$uhr->delete();
		}
		else
		{
			//otherwise, create it
			$uhr = new UserHasRoles();
			$uhr->idUser = $idUser;
			$uhr->rolesId = $idRole;
			if($uhr->save())
			{
				$text = Yii::t('app', 'Yes');
			}
		}
		echo CJSON::encode(array('success'=>true, 'text'=>$text));
	}
	
}

app/views/user/form.php
<?php $update = isset($update) ? $update : false; ?>
<h4><?php echo ($update) ? Yii::t('app', 'Update user') : Yii::t('app', 'Create user'); ?></h4>

	<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	    'id'=>'user-form',
	    'htmlOptions'=>array('class'=>'well', 'enctype'=>'multipart/form-data'),
	)); ?>

    <?php echo CHtml::errorSummary($model);?>
    
    <?php echo $form->textFieldRow($model, 'name', array('class'=>'span5', 'placeholder' => Yii::t('app', 'Alias'))); ?>
    
    <?php echo $form->textFieldRow($model, 'email', array('class'=>'span5', 'placeholder' => Yii::t('app', 'Email'))); ?>

    <?php
    //if(!$update)
    //{
        echo $form->passwordFieldRow($model, 'password', array('class'=>'span5', 'placeholder' => Yii::t('app', 'Password')));

        echo $form->passwordFieldRow($model, '_repeatPassword', array('class'=>'span5', 'placeholder' => 'Repetir contraseña'));
    //}
    ?>
    <?php echo $form->dropDownListRow($model, 'idJob', CHtml::listData(Job::model()->findAll(), 'idJob', 'job'),
        array('class'=>'span5', 'empty'=>'Seleccionar Puesto')); ?>
    <?php //echo $form->dropDownListRow($model, 'idCompany', CHtml::listData(Company::model()->findAll(), 'idCompany', 'company'),
        //array('class'=>'span5', 'empty'=>'Seleccionar empresa')); ?>

	<?php //echo $form->dropDownListRow($model, 'idConsultant', CHtml::listData(Consultant::model()->findAll(), 'idConsultant', 'consultant'),
   //     array('class'=>'span5', 'empty'=>'Seleccionar consultor')); ?>
   
    <?php //echo $form->dropDownListRow($model, 'sex', array(0=>'Femenino', 1=>'Masculino'),
        //array('class'=>'span5', 'empty'=>'Seleccionar sexo')); ?>

    <?php //$model->generatePictureInput(); ?>


</br></br>
<div>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Cancelar',
        'url' => array('/user/index'),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'=>'submit', 
        'label'=>$update ? 'Actualizar' : 'Crear',
        'htmlOptions' => array('class'=>'btn btn-primary'),
    )); ?>
</div>

<?php $this->endWidget(); ?>

app/views/user/index.php
<div class="buttons">
	<?php
	$params = array_merge($_GET, array('export'=>true));
	$this->widget('bootstrap.widgets.TbButtonGroup',array(
		'buttons'=>array(
			array('label'=> Yii::t('app', 'Create user'), 'type'=>'inverse', 
				'url'=>array('create')),
			array('label'=>Yii::t('app', 'Export'), 'type'=>'inverse',
					'url'=>app()->controller->createUrl('index', $params)),
			)
	));?>
</div>

<div style="text-align:center">
	<h3>Usuarios</h3>
</div>

<div style="width:100%; margin:0 auto;">

	<?php
	$columns = array(
		'username'=>array(
			'class' => 'ETbEditableColumn',
			'name' => 'name',
			'sortable'=>true,
			'editable' => array(
				'url' => $this->createUrl('changeAttributeUser'),
				'placement' => 'right',
				'inputclass' => 'span3',
                'title' => 'Ingresar Alias'
			),
			'filter' => CHtml::ListData(User::model()->findAll(array('order' => 'name ASC')), 'name', 'name')
		),

		'permissions'=>array(
			'header' => 'Permisos',
			'class' => 'TbDataColumn',
			'id' => 'permissions',
			'value' => '$data->getRolesList()'
		),
		
		'email'=>array(
			'class' => 'TbDataColumn',
			'name' => 'email',
			'sortable'=>true,
		),
		'idJob'=>array(
			'class' => 'CDataColumn',
			'name' => 'idJob',
			'value'=>'$data->getJobName()',
			'filter' => CHtml::ListData(Job::model()->findAll(array('order' => 'job ASC')), 'idJob', 'job')
		),

	);

	$this->widget('bootstrap.widgets.TbExtendedGridView', array(
		'id' => 'user-grid',
		'dataProvider' => $model->search(),
		'filter' => $model,
		'ajaxUrl'=>array('index'),
		'fixedHeader' => true,
		'headerOffset' => 40,
		'type' => 'table striped bordered condensed',
		'responsiveTable' => true,
		'rowCssClassExpression'=>"'userRow'",
		'columns' => array_merge(array_values($columns),
			array(array(
				'class' => 'bootstrap.widgets.TbButtonColumn',
				'header'=>'Acciones',
				'htmlOptions'=>array('style'=>'width:150px; text-align:center;'),
				'buttons'=>array(
					'delete'=>array(
						'options'=>array('class'=>'btn btn-mini btn-delete-row'),
						'url'=>'app()->controller->createUrl("delete",array(
							"id"=>$data->primaryKey, "key"=>uKey("deleteUser".$data->primaryKey)))'
					),
					'update'=>array(
						'label'=>Yii::t('app', 'Edit'),
						'options'=>array('class'=>'btn btn-mini'),
						'url'=>'app()->controller->createUrl("update",array(
							"id"=>$data->primaryKey, "key"=>uKey("updateUser".$data->primaryKey)))'
					),
					'rolesAndPerms'=>array(
						'url'=>'CHtml::normalizeUrl(array("userRolesPermissions",
							"idUser"=>$data->primaryKey,
							"key"=>uKey("perms".$data->primaryKey)))',
						'label'=>Yii::t('app', 'Permissions'),
						'options'=>array('class'=>'btn btn-mini open-modal-small btn-key-row'),
					),
				),
				'template'=>'{update} {rolesAndPerms} {delete}',
				),
			)),
		));
	?>
</div>

<?php
cs()->registerScript(__FILE__ . '_smallUserModal', '
		$("body").on("click", ".open-modal-small", function(e){
			var $this = $(this);
			var $modal = $("#smallUserModal");
			$modal.html("<i class=\"icon-spinner icon-spin icon-large\"></i>");
			$modal.modal("show");
			$.ajax($this.attr("href"), {
				"success": function(data) {
					$modal.html(data);
				},

				"error": function(x,s,e)	{
					$modal.html(x.responseText);
				}

			});
			e.preventDefault();
		});
	');

$this->beginWidget('bootstrap.widgets.TbModal', array('id' => 'smallUserModal',
	 'htmlOptions'=>array('class'=> 'modal-add'))); 
$this->endWidget() ;

cs()->registerScript(__FILE__ . '_toggleLinks', '
jQuery("body").on("click", ".togglelink", function(eventObject){
	$this = jQuery(this);
	$.ajax($this.data("togglelinkurl"),
		{
			dataType:"json",
			type: "POST",
			success: function(data){
				$this.html(data.text);
			}
		}
	);
	eventObject.preventDefault();
});');

?>

app/views/user/userRoles.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'addNewRecord',
    'enableAjaxValidation'=>true,
)); ?>
<div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h4>"<?php echo  Yii::t('app', 'Roles for {user}', array('{user}'=>$user->name)); ?>"</h4>
</div>

<div class="modal-body" style="max-height: 310px; overflow: scroll;">
	
	<?php foreach($roles as $role)
	{ ?>
		<div class="row-fluid">
			<div class="span12">
				<?php echo $role->name . '?: ' . CHtml::link($user->hasRole($role->getPrimaryKey())? Yii::t('app', 'Yes') : Yii::t('app', 'No'), '#toggleRole', array(
					'class'=>'togglelink',
					'data-togglelinkurl'=>$this->createUrl('toggleRolesForUser', array('idUser'=>$user->getPrimaryKey(), 'idRole'=>$role->getPrimaryKey())),
				));?>
			</div>
		</div>
	<?php } ?>
	
</div>
<div class="modal-footer">
	<?php echo  CHtml::link('Volver', '#closeUserView', array('data-dismiss'=>"modal", 'class'=>'btn btn-primary'));?>
</div>

<?php 
$this->endWidget(); 