app/models/Job.php
<?php

/**
 * This is the model class for table "job".
 *
 * The followings are the available columns in table 'job':
 * @property integer $idJob
 * @property string $job
 */
class Job extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Job the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'job';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('idJob', 'numerical', 'integerOnly'=>true),
            array('job', 'length', 'max'=>50),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        //province
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idJob' => Yii::t('app', 'Id Job'),
			'job' => Yii::t('app', 'Job'),
		);
	}

	public function scopes() {
		return array(
			'findAllWithOrder' => array('order' => 'job ASC'),
		);
	}
	/*
	public function defaultScope()
	{
		return array(
			'condition' => 'status = 1'
		);
	}*/

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */

    public function getList() {

        $sql = "SELECT * FROM job;";
        $command=Yii::app()->db->createCommand($sql);
        return $data=$command->queryAll();
	}
	
	public function getJob()
	{
		return $this->job ? $this->job : "No";
	}

	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idJob',$this->idJob);
		$criteria->compare('job',$this->job,true);

		$sort = new CSort();
		$sort->defaultOrder = 'job ASC';

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>$sort,
			'pagination'=>array(
				'pageSize'=>app()->controller->getItemsPerPage()
			),
		));
	}
	
	public function delete()
	{

			$criteria = new CDbCriteria();
			$criteria->condition = 'idJob = :id';
			return parent::delete();
    }

}

app/controllers/JobController.php
<?php

class JobController extends AdminController
{
	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
    public function actionIndex(){
		$model = new Job();
		$model->unsetAttributes();

		if(isset($_GET['Job']))
		{
			$model->attributes = $_GET['Job'];
		}

		$this->render('index', array(
			'model' => $model,
		));
    }
    
	public function actionCreate()
	{
		$model = new Job();
		
		if(isset($_POST['Job']))
       	{
            $model->attributes=$_POST['Job'];
	        if($model->save())
	        {
	            $this->redirect(array('index'));
	        }
        }
		$this->render('form', array('model'=>$model));
    }
    
	public function actionChangeAttributeManual()
	{
		Yii::import('bootstrap.widgets.TbEditableSaver');
		$es = new TbEditableSaver('Job');
	    $es->update();
    }

    public function actionDelete($id, $key) {
		$model = Job::model()->findByPk(CPropertyValue::ensureInteger($id));

		if ($model instanceof Job) 
		{			
			try {
				$model->delete($id);
			} catch (Exception $e) {
				throw new Exception($e);
				
				throw new CHttpException(500, Yii::t('app', 'The country is being used and cannot be deleted'));
			}
			if (!Yii::app()->getRequest()->getIsAjaxRequest())
			{
				$this->redirect(array('index'));
			}
		} else{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}    

}

app/views/job/form.php
<h4>Agregar Puesto de Trabajo</h4>


	<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	    'id'=>'document-form',
	    'htmlOptions'=>array('class'=>'well', 'enctype'=>'multipart/form-data'),
	)); ?>


<?php //CAMPOS
        echo $form->textFieldRow($model, 'job', array('class'=>'span5', 'placeholder' =>'Puesto...'));
    ?>
</br></br>
<div>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Cancelar',
        'url' => array('/job/index'),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'=>'submit', 
        'label'=>'Guardar',
        'htmlOptions' => array('class'=>'btn btn-primary'),
    )); ?>
</div>

<?php $this->endWidget(); ?>

app/views/job/index.php
<?php $this->widget('bootstrap.widgets.TbButtonGroup',array(
        'buttons'=>array(
            array('label'=> Yii::t('app', 'Agregar Puesto'), 'type'=>'inverse', 
                'url'=>array('create')),),
            
    ));?>
<div style="text-align:center">
    <h3>Puestos de Trabajo</h3>
</div>

<div style="width:100%; margin:0 auto;">
    <?php
        $columns = array(
            'name'=>array(
                'class' => 'ETbEditableColumn',
                'name' => 'job',
                'editable' => array(
                    'url' => $this->createUrl('changeAttributeManual'),
                    'placement' => 'right',
                    'inputclass' => 'span2',
                    'title' => 'Insertar Trabajo'
                ),
            ),
       );

        $this->widget('bootstrap.widgets.TbExtendedGridView', array(
            'id' => 'provider-grid',
            'dataProvider' => $model->search(),
            'filter' => $model,
            'ajaxUrl'=> array('index'),
            'fixedHeader' => true,
            'headerOffset' => 40,
            'type' => 'table striped bordered condensed',
            'responsiveTable' => true,
            'columns' => array_merge(
                array_values($columns),
                array(array(
                    'class' => 'bootstrap.widgets.TbButtonColumn',
                    'header'=>'Acciones',
                    'htmlOptions'=>array('style'=>'width:150px; text-align:center;'),
                    'buttons'=>array(
                        'delete'=>array(
                            'icon'=>'icon-trash',
                            'label'=>'Eliminar',
                            'options'=>array('class'=>'btn btn-mini'),
                            'url'=>'app()->controller->createUrl("delete",array(
                                "id"=>$data->primaryKey, "key"=>uKey("delete".$data->primaryKey)))'
                        ),
                    ),
                    
                    'template'=>'{delete}',
                ))
            ),
        )); 
    ?>

    <?php $this->widget('application.components.PageSizeComponent'); ?>
</div>